### ISSUE TITLE
🐛 Bug Report: Generated app server - `Invalid role(s): []` error

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3949]
### What happened?

based on the a discord thread: https://discord.com/channels/757179260417867879/1022628873210429511

![image](https://user-images.githubusercontent.com/39680385/192026193-50ab7ae7-00ea-4504-8225-2cce8345e357.png)

### How to reproduce

- create a project with a service
- clone and run the app
- login with admin/admin
- make any other request

### Amplication version

1.0.0

**Comment by shubhwip** [comment]
Looks similar to #3745

**Comment by abrl91** [comment]
> 

Thank you. It's similar but in this case, it is not in a test

**Comment by tupe12334** [comment]
This issue is resolved in #3957

**Comment by sukiejosh** [comment]
I am still facing the issue 

![Screenshot 2022-09-30 182230](https://user-images.githubusercontent.com/44656210/193323888-6f68453d-eed8-4033-9258-b83a7c432678.png)

My Payload

![Screenshot 2022-09-30 182600](https://user-images.githubusercontent.com/44656210/193324263-56cf0756-ec53-454c-aa88-1e82e0bbab20.png)

**Comment by tupe12334** [comment]
> I am still facing the issue
> 
> ![Screenshot 2022-09-30 182230](https://user-images.githubusercontent.com/44656210/193323888-6f68453d-eed8-4033-9258-b83a7c432678.png)
> 
> My Payload
> 
> ![Screenshot 2022-09-30 182600](https://user-images.githubusercontent.com/44656210/193324263-56cf0756-ec53-454c-aa88-1e82e0bbab20.png)

Please wait for the 1.0.2 release

**Comment by sukiejosh** [comment]
> > I am still facing the issue
> > ![Screenshot 2022-09-30 182230](https://user-images.githubusercontent.com/44656210/193323888-6f68453d-eed8-4033-9258-b83a7c432678.png)
> > My Payload
> > ![Screenshot 2022-09-30 182600](https://user-images.githubusercontent.com/44656210/193324263-56cf0756-ec53-454c-aa88-1e82e0bbab20.png)
> 
> Please wait for the 1.0.2 release

Alright..thank you
