### ISSUE TITLE
🐛 Bug Report: `npx nx db:migrate:dev` amplication-plugin-api fails for when migration needs interactive response 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7546]
### What happened?

Running prisma interactive commands through nx is currently ending up in an bad state.
i.e. when creating migrations that will touch / delete data, prisma cli will ask user for a confirmation, when this happen running the nx command, the result will be an error.

### What you expected to happen

commands like npx nx db:migrate:dev amplication-plugin-api should proceed as expected

### How to reproduce

run npx nx db:migrate:dev amplication-plugin-api

**Comment by overbit** [comment]
Consider using either of the following:
- our custom executor https://github.com/amplication/amplication/pull/7490/commits/2cecb6075ee0727a1b0cd19edcc4560e2f3a93e7
- https://www.npmjs.com/package/@nx-tools/nx-prisma

**Comment by mulygottlieb** [comment]
@overbit TTBOMK this is already fixed - right?
Please more the ticket status if so

**Comment by overbit** [comment]
This issue is still present when db is not in line with migrations and prisma will ask for permission to delete data. 

Moreover, ` https://www.npmjs.com/package/@nx-tools/nx-prisma` won't help us here as it suffer from issue (https://github.com/gperdomor/nx-tools/issues/597)

The only options we have is https://github.com/amplication/amplication/commit/2cecb6075ee0727a1b0cd19edcc4560e2f3a93e7

**Comment by mulygottlieb** [comment]
Backlogging it for now since we can run the migrations not via nx locally.
